#! /bin/sh

# Fix Java windows
export _JAVA_AWT_WM_NONREPARENTING=1

if [ -x $HOME/bin/bspwm_dual_monitor ]; then
	$HOME/bin/bspwm_dual_monitor
fi

pgrep -x sxhkd > /dev/null || sxhkd &
ulauncher --hide-window --no-window-shadow &
nitrogen --restore &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc wm -O DP-2 DP-0
bspc monitor -d V VI VII VIII IX X I II III IV
bspc monitor DP-2 -d 1 2 3 4
bspc monitor DP-0 -d 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           1

bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off
bspc rule -a pia-client state=floating
